/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testvideo_MainActivity */

#ifndef _Included_com_example_testvideo_MainActivity
#define _Included_com_example_testvideo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_testvideo_MainActivity_REQ_CODE_TAKE_VIDEO
#define com_example_testvideo_MainActivity_REQ_CODE_TAKE_VIDEO 9999L
/*
 * Class:     com_example_testvideo_MainActivity
 * Method:    helloLog
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jstring JNICALL Java_com_example_testvideo_MainActivity_helloLog
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
